system:
  host: 127.0.0.1
  port: 8080
  env: test
#  env: release

mysql:
  host: 127.0.0.1
  port: 3306
  db: blog
  user: root
  password: root
  config: 'charset=utf8&parseTime=True&loc=Local'
  log_level: dev
  max_idle_conns: 10
  max_open_conns: 100
  max_lifetime: 4

redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0
  pool_size: 100

logger:
  level: info
  prefix: blog
  director: log
  show_line: true
  log_in_console: true

jwt:
  secret: KarlXuBlog
  expires: 2
  issuer: KarlXu
